# Generated by Django 3.1.2 on 2021-01-03 14:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_title', models.CharField(max_length=100)),
                ('document_hash', models.TextField()),
                ('public_key', models.TextField()),
                ('signature', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyTable',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_name', models.CharField(default='Имя ключа', max_length=100, verbose_name='Название подписи')),
                ('key', models.TextField(unique=True)),
                ('dateOfCreation', models.DateTimeField(default=datetime.datetime(2021, 1, 3, 19, 16, 30, 957538))),
                ('dateOfExpiration', models.DateTimeField(default=datetime.datetime(2021, 2, 2, 19, 16, 30, 957538), verbose_name='Срок действия подписи')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
