# Generated by Django 3.1.2 on 2021-01-03 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Signature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytable',
            name='dateOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 15, 54, 24, 801392, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfExpiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 15, 54, 24, 801392, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
    ]
