# Generated by Django 3.1.2 on 2021-01-06 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Signature', '0003_auto_20210104_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytable',
            name='dateOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 13, 2, 17, 645000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfExpiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 13, 2, 17, 645000, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
    ]
