# Generated by Django 3.1.2 on 2021-01-06 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Signature', '0004_auto_20210106_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocument',
            name='key_table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Signature.keytable'),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 15, 57, 58, 383281, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfExpiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 15, 57, 58, 383281, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
    ]
