# Generated by Django 3.1.2 on 2021-01-09 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Signature', '0006_auto_20210110_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytable',
            name='dateOfCreation',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 20, 8, 20, 502959, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfExpiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 20, 8, 20, 502959, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
    ]
