# Generated by Django 3.1.2 on 2021-01-10 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Signature', '0008_auto_20210110_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytable',
            name='dateOfCreation',
            field=models.DateField(default=datetime.datetime(2021, 1, 10, 12, 15, 53, 423504, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfExpiration',
            field=models.DateField(default=datetime.datetime(2021, 2, 9, 12, 15, 53, 423504, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='key_name',
            field=models.CharField(default='Имя ключа', max_length=100, unique=True, verbose_name='Название подписи'),
        ),
    ]
