# Generated by Django 3.1.2 on 2021-01-22 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Signature', '0011_auto_20210122_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keytable',
            name='dateOfCreation',
            field=models.DateField(default=datetime.datetime(2021, 1, 22, 15, 50, 36, 340257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfExpiration',
            field=models.DateField(default=datetime.datetime(2021, 2, 21, 15, 50, 36, 340257, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 1, 22, 15, 50, 36, 340257, tzinfo=utc)),
        ),
    ]
