# Generated by Django 3.1.2 on 2021-01-23 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Signature', '0012_auto_20210122_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocument',
            name='date_for_logs',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 16, 11, 36, 997119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfCreation',
            field=models.DateField(default=datetime.datetime(2021, 1, 23, 16, 11, 36, 997119, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfExpiration',
            field=models.DateField(default=datetime.datetime(2021, 2, 22, 16, 11, 36, 997119, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 1, 23, 16, 11, 36, 997119, tzinfo=utc)),
        ),
    ]
