# Generated by Django 3.1.2 on 2021-04-15 07:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Signature', '0013_auto_20210123_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVdDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=100, unique=True)),
                ('document_hash', models.TextField()),
                ('date_of_creation', models.DateField(default=datetime.datetime(2021, 4, 15, 7, 36, 59, 471419, tzinfo=utc))),
                ('date_for_logs', models.DateTimeField(default=datetime.datetime(2021, 4, 15, 7, 36, 59, 471419, tzinfo=utc))),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfCreation',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 7, 36, 59, 471419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfExpiration',
            field=models.DateField(default=datetime.datetime(2021, 5, 15, 7, 36, 59, 471419, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='date_for_logs',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 7, 36, 59, 471419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 4, 15, 7, 36, 59, 471419, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='TestVSignedForDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.BinaryField()),
                ('signature', models.BinaryField()),
                ('signed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Signature.testvddocument')),
            ],
        ),
        migrations.CreateModel(
            name='TestVKeyTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(default='Имя ключа', max_length=100, unique=True, verbose_name='Название подписи')),
                ('key', models.TextField(unique=True)),
                ('dateOfCreation', models.DateField(default=datetime.datetime(2021, 4, 15, 7, 36, 59, 471419, tzinfo=utc))),
                ('dateOfExpiration', models.DateField(default=datetime.datetime(2021, 5, 15, 7, 36, 59, 471419, tzinfo=utc), verbose_name='Срок действия подписи')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
