# Generated by Django 3.1.2 on 2021-04-23 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Signature', '0016_auto_20210423_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testvddocument',
            name='document_hash',
        ),
        migrations.AddField(
            model_name='testvsignedfordocument',
            name='document_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfCreation',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 10, 32, 42, 644579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfExpiration',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 10, 32, 42, 644579, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='date_for_logs',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 10, 32, 42, 644579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 10, 32, 42, 644579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testvddocument',
            name='date_for_logs',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 10, 32, 42, 644579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testvddocument',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 10, 32, 42, 644579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testvkeytable',
            name='dateOfCreation',
            field=models.DateField(default=datetime.datetime(2021, 4, 23, 10, 32, 42, 644579, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testvkeytable',
            name='dateOfExpiration',
            field=models.DateField(default=datetime.datetime(2021, 5, 23, 10, 32, 42, 644579, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
    ]
