# Generated by Django 3.1.2 on 2021-04-29 07:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Signature', '0019_auto_20210429_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testvddocument',
            name='key_table_id',
        ),
        migrations.AddField(
            model_name='testvsignedfordocument',
            name='key_table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Signature.testvkeytable'),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfCreation',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 7, 28, 32, 451615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='keytable',
            name='dateOfExpiration',
            field=models.DateField(default=datetime.datetime(2021, 5, 29, 7, 28, 32, 451615, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='date_for_logs',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 7, 28, 32, 451615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 7, 28, 32, 451615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testvddocument',
            name='date_for_logs',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 29, 7, 28, 32, 451615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testvddocument',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 7, 28, 32, 451615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testvkeytable',
            name='dateOfCreation',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 7, 28, 32, 451615, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testvkeytable',
            name='dateOfExpiration',
            field=models.DateField(default=datetime.datetime(2021, 5, 29, 7, 28, 32, 451615, tzinfo=utc), verbose_name='Срок действия подписи'),
        ),
        migrations.AlterField(
            model_name='testvsignedfordocument',
            name='date_signed',
            field=models.DateField(default=datetime.datetime(2021, 4, 29, 7, 28, 32, 451615, tzinfo=utc)),
        ),
    ]
